<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Merchant Application</name>
   <tag></tag>
   <elementGuidId>65590993-d213-4e11-afec-3fd24981f489</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.mrgn-bot-xs</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//section[@id='main-content']/section/div/div/div/section/header/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>604db6f4-4065-47c5-b0b1-36c22acf8fdf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mrgn-bot-xs</value>
      <webElementGuid>9de13f2d-87f8-4f8e-a174-10249d6b74d1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Merchant Application                                                                        </value>
      <webElementGuid>5b73230c-742d-421d-b3d0-55ccdf5c3913</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;main-content&quot;)/section[@class=&quot;wrapper&quot;]/div[@class=&quot;row row-padding&quot;]/div[@class=&quot;col-sm-12&quot;]/div[@class=&quot;form&quot;]/section[@class=&quot;panel panel-apply panel-1&quot;]/header[@class=&quot;panel-heading panel-padding&quot;]/div[@class=&quot;mrgn-bot-xs&quot;]</value>
      <webElementGuid>f3cc092b-9f5f-45ef-92b0-87dac90edf5f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//section[@id='main-content']/section/div/div/div/section/header/div</value>
      <webElementGuid>68d4a1a7-283a-49bd-b43a-dacd8e3ae6e7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/section/header/div</value>
      <webElementGuid>35827dfc-4c03-4e66-8823-1ae5a47ad72a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Merchant Application                                                                        ' or . = 'Merchant Application                                                                        ')]</value>
      <webElementGuid>bfe80b3c-28c0-46c4-abf8-a66075d55c84</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
