<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_Your state province</name>
   <tag></tag>
   <elementGuidId>c070c19a-668d-401c-abb6-fd800d0ec73e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#states</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='states']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>33e17245-8437-43c3-b47a-7c440e79936d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>state</value>
      <webElementGuid>4ed49481-b9c3-470b-a818-8952e937baa8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control border-grey</value>
      <webElementGuid>c33ef02b-a578-42eb-be98-946c023c9fcf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>states</value>
      <webElementGuid>82e230ae-09b5-4b27-bfdf-38af43e21286</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Your state / province (optional)nullÍsland</value>
      <webElementGuid>cb9c6b13-df0b-4b8d-8891-b5cdf979db61</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;states&quot;)</value>
      <webElementGuid>b5dd5430-f265-42df-9712-aff8919865e6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='states']</value>
      <webElementGuid>9d6fc867-dd06-439e-bf0e-65423d9b912b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='state_input_wrapper']/select</value>
      <webElementGuid>3d986080-2704-4d9c-94fd-1f39172960d4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/select</value>
      <webElementGuid>7ef202a5-4e22-4b6b-9875-5fb0948cb809</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@name = 'state' and @id = 'states' and (text() = 'Your state / province (optional)nullÍsland' or . = 'Your state / province (optional)nullÍsland')]</value>
      <webElementGuid>2abcf5e2-9ec9-4479-aa98-57a1bbecf58f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
